package com.stokvault.report;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Renders a Statement as a PDF (SDD 1.3: "exportable financial reports (PDF/CSV)").
 *
 * A PDF is a text format underneath: numbered objects (the catalog, the page tree, fonts and one
 * content stream per page) followed by a cross-reference table giving each object's byte offset.
 * This small writer produces that structure directly, so no third-party PDF library is needed.
 * It uses the standard fonts every PDF viewer has built in (Helvetica, Courier) and A4 pages; the
 * table is set in Courier so its columns line up.
 */
public final class StatementPdf {

    private static final float PAGE_WIDTH = 595;   // A4 in points (1/72 inch)
    private static final float PAGE_HEIGHT = 842;
    private static final float MARGIN = 40;
    private static final float TABLE_FONT_SIZE = 8;
    private static final float CHAR_WIDTH = TABLE_FONT_SIZE * 0.6f; // Courier: every character is 0.6 em wide
    private static final int MAX_CHARS = (int) ((PAGE_WIDTH - 2 * MARGIN) / CHAR_WIDTH);

    private StatementPdf() {
    }

    private record Line(String font, float size, String text, float gapBefore) {
    }

    public static byte[] render(Statement statement) {
        List<Line> lines = new ArrayList<>();
        lines.add(new Line("F2", 15, statement.title(), 0));
        statement.subtitle().forEach(s -> lines.add(new Line("F1", 9, s, 3)));

        int[] widths = columnWidths(statement);
        lines.add(new Line("F4", TABLE_FONT_SIZE, formatRow(statement.headers(), widths, statement), 14));
        lines.add(new Line("F3", TABLE_FONT_SIZE, "-".repeat(Math.min(MAX_CHARS, sum(widths) + widths.length - 1)), 1));
        if (statement.rows().isEmpty()) {
            lines.add(new Line("F1", 9, "No entries.", 4));
        }
        statement.rows().forEach(row -> lines.add(new Line("F3", TABLE_FONT_SIZE, formatRow(row, widths, statement), 2)));
        for (int i = 0; i < statement.footer().size(); i++) {
            lines.add(new Line("F2", 9, statement.footer().get(i), i == 0 ? 12 : 3));
        }
        return write(paginate(lines));
    }

    /** Fits columns into the page width, shrinking the widest ones if needed. */
    private static int[] columnWidths(Statement s) {
        int[] widths = new int[s.headers().size()];
        for (int c = 0; c < widths.length; c++) {
            widths[c] = s.headers().get(c).length();
            for (List<String> row : s.rows()) {
                widths[c] = Math.max(widths[c], row.get(c) == null ? 0 : row.get(c).length());
            }
        }
        while (sum(widths) + widths.length - 1 > MAX_CHARS) {
            int widest = 0;
            for (int c = 1; c < widths.length; c++) {
                if (widths[c] > widths[widest]) {
                    widest = c;
                }
            }
            widths[widest]--;
        }
        return widths;
    }

    private static String formatRow(List<String> cells, int[] widths, Statement s) {
        StringBuilder row = new StringBuilder();
        for (int c = 0; c < widths.length; c++) {
            String v = cells.get(c) == null ? "" : cells.get(c);
            if (v.length() > widths[c]) {
                v = v.substring(0, Math.max(0, widths[c] - 1)) + "~";
            }
            boolean right = s.numericColumns().contains(c);
            row.append(right ? " ".repeat(widths[c] - v.length()) + v : v + " ".repeat(widths[c] - v.length()));
            if (c < widths.length - 1) {
                row.append(' ');
            }
        }
        return row.toString();
    }

    /** Splits lines into pages and turns each page into a PDF content stream. */
    private static List<String> paginate(List<Line> lines) {
        List<StringBuilder> pages = new ArrayList<>();
        StringBuilder page = null;
        float y = 0;
        for (Line line : lines) {
            float step = line.size() + line.gapBefore() + 2;
            if (page == null || y - step < MARGIN + 20) {
                page = new StringBuilder();
                pages.add(page);
                y = PAGE_HEIGHT - MARGIN;
            } else {
                y -= step;
            }
            page.append("BT /").append(line.font()).append(' ').append(fmt(line.size())).append(" Tf ")
                    .append(fmt(MARGIN)).append(' ').append(fmt(y - line.size())).append(" Td (")
                    .append(escape(line.text())).append(") Tj ET\n");
        }
        String generated = "Generated by StokVault on " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
        List<String> streams = new ArrayList<>();
        for (int i = 0; i < pages.size(); i++) {
            String footer = generated + "  |  Page " + (i + 1) + " of " + pages.size();
            streams.add(pages.get(i) + "BT /F1 7 Tf " + fmt(MARGIN) + " " + fmt(MARGIN - 10) + " Td (" + escape(footer) + ") Tj ET\n");
        }
        return streams;
    }

    /** Assembles the objects and the cross-reference table. */
    private static byte[] write(List<String> pageStreams) {
        int pageCount = pageStreams.size();
        int firstPageObject = 7; // 1 catalog, 2 pages, 3-6 fonts
        List<String> objects = new ArrayList<>();
        objects.add("<< /Type /Catalog /Pages 2 0 R >>");
        StringBuilder kids = new StringBuilder();
        for (int i = 0; i < pageCount; i++) {
            kids.append(firstPageObject + i * 2).append(" 0 R ");
        }
        objects.add("<< /Type /Pages /Kids [" + kids.toString().trim() + "] /Count " + pageCount + " >>");
        objects.add(font("Helvetica"));
        objects.add(font("Helvetica-Bold"));
        objects.add(font("Courier"));
        objects.add(font("Courier-Bold"));
        for (int i = 0; i < pageCount; i++) {
            int contentObject = firstPageObject + i * 2 + 1;
            objects.add("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 " + fmt(PAGE_WIDTH) + " " + fmt(PAGE_HEIGHT) + "]"
                    + " /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R /F4 6 0 R >> >> /Contents " + contentObject + " 0 R >>");
            byte[] content = pageStreams.get(i).getBytes(StandardCharsets.ISO_8859_1);
            objects.add("<< /Length " + content.length + " >>\nstream\n" + pageStreams.get(i) + "endstream");
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        write(out, "%PDF-1.4\n");
        List<Integer> offsets = new ArrayList<>();
        for (int i = 0; i < objects.size(); i++) {
            offsets.add(out.size());
            write(out, (i + 1) + " 0 obj\n" + objects.get(i) + "\nendobj\n");
        }
        int xref = out.size();
        StringBuilder table = new StringBuilder("xref\n0 " + (objects.size() + 1) + "\n0000000000 65535 f \n");
        offsets.forEach(offset -> table.append(String.format("%010d 00000 n \n", offset)));
        table.append("trailer\n<< /Size ").append(objects.size() + 1).append(" /Root 1 0 R >>\nstartxref\n")
                .append(xref).append("\n%%EOF\n");
        write(out, table.toString());
        return out.toByteArray();
    }

    private static String font(String name) {
        return "<< /Type /Font /Subtype /Type1 /BaseFont /" + name + " /Encoding /WinAnsiEncoding >>";
    }

    /** PDF strings are wrapped in ( ); backslashes and brackets must be escaped. Non-Latin text becomes '?'. */
    static String escape(String text) {
        StringBuilder s = new StringBuilder();
        for (char ch : (text == null ? "" : text).toCharArray()) {
            if (ch == '\\' || ch == '(' || ch == ')') {
                s.append('\\').append(ch);
            } else if (ch < 32 || ch > 255) {
                s.append('?');
            } else {
                s.append(ch);
            }
        }
        return s.toString();
    }

    private static String fmt(float value) {
        return value == (int) value ? Integer.toString((int) value) : String.format(java.util.Locale.ROOT, "%.2f", value);
    }

    private static int sum(int[] values) {
        int total = 0;
        for (int v : values) {
            total += v;
        }
        return total;
    }

    private static void write(ByteArrayOutputStream out, String text) {
        out.writeBytes(text.getBytes(StandardCharsets.ISO_8859_1));
    }
}
